extends Node

# MUY IMPORTANTE: SI SE COLOCA CUALQUIER COSA EN EL SCENE TREE, HAY QUE PONER UN MULTIPLAYER SPAWNER PARA ESTE

# CADA VEZ Q SE USA ADD_CHILD, ASEGURARSE Q TIENE UN SYNCHRONIZER PUESTO


# MUY IMPORTANTE: SI SE COLOCA CUALQUIER COSA EN EL SCENE TREE, HAY QUE PONER UN MULTIPLAYER SPAWNER PARA ESTE
